### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/appengine-cloudsql-native-mysql-datanucleus-jpa-demo-java#2]
The buiild fails with the following error:

Exception in thread "main" Plugin (Bundle) "org.datanucleus" is already registered. Ensure you dont have multiple JAR versions of the same plugin in the classpath. The URL "file:~/.m2/repository/org/datanucleus/datanucleus-core/3.2.2/datanucleus-core-3.2.2.jar" is already registered, and you are trying to register an identical plugin located at URL "file:~/.m2/repository/org/datanucleus/datanucleus-core/3.2.5/datanucleus-core-3.2.5.jar."

Tried with the following exclusion:

```
<exclusions>
    <exclusion>
      <groupId>org.datanucleus</groupId>
      <artifactId>datanucleus-core</artifactId>
    </exclusion>
  </exclusions>
```

then got another error:
Exception in thread "main" java.lang.NoSuchMethodError: org.datanucleus.metadata.AbstractMemberMetaData.setPersistenceModifier(Lorg/datanucleus/metadata/FieldPersistenceModifier;)V
    at org.datanucleus.api.jpa.metadata.JPAAnnotationReader.newMetaDataForMember(JPAAnnotationReader.java:2512)
    at org.datanucleus.api.jpa.metadata.JPAAnnotationReader.processMemberAnnotations(JPAAnnotationReader.java:1302)
    at org.datanucleus.metadata.annotations.AbstractAnnotationReader.getMetaDataForClass(AbstractAnnotationReader.java:177)
    at org.datanucleus.metadata.annotations.AnnotationManagerImpl.getMetaDataForClass(AnnotationManagerImpl.java:171)
    at org.datanucleus.metadata.MetaDataManager.loadAnnotationsForClass(MetaDataManager.java:2722)
    at org.datanucleus.metadata.MetaDataManager.loadPersistenceUnit(MetaDataManager.java:980)
    at org.datanucleus.enhancer.DataNucleusEnhancer.getFileMetadataForInput(DataNucleusEnhancer.java:796)
    at org.datanucleus.enhancer.DataNucleusEnhancer.enhance(DataNucleusEnhancer.java:513)
    at org.datanucleus.enhancer.DataNucleusEnhancer.main(DataNucleusEnhancer.java:1281)

**Comment by andyjefferson** [comment]
Why you would go around excluding jars I've no idea. Far easier to just update the datanucleus jars to the current release and all compiles. See Issue #3
